sudo: required
services:
  - docker
before_install:
  - docker build -t laurentiulbg/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true laurentiulbg/docker-react npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "eu-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-079969817990"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY